[project]
name = "enpkg"
version = "0.0.2"
description = "ENPKG FULL"
authors = [
    {name = "Pierre-Marie Allard", email= "pierre-marie.allard@unifr.ch"},
    {name = "Loïc Le Grégam", email = "Loic.Legregam@unige.ch"}
]
license = "GPL-3.0-only"
packages = [
    {include = "monolith", from = "enpkg"}
]
readme = "README.md"

[project.urls]
homepage = "https://github.com/enpkg/enpkg_full"
repository = "https://github.com/enpkg/enpkg_full"
documentation = "https://github.com/enpkg/enpkg_full"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
networkx = "^3.6.1"
matchms = "^0.20.0"
pandas = "^3.0.0"
plotly = "^6.5.2"
pyyaml = "^6.0.3"
rdflib = "^7.5.0"
requests = "^2.32.5"
scipy = "^1.17.0"
spec2vec = "^0.8.0"
memo-ms = "^0.1.4"
opentree = "^1.0.1"
pydantic = "^2.12.5"
downloaders = "^1.0.22"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"